replicaCount: 2
image:
  tag: "c454d932816b4af0262c8c8a612a118cc3159919"

ingress:
  host: "stage.medisnapdiagnostics.com"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'