replicaCount: 1
image:
  tag: "dev-initial"

ingress:
  host: "dev.medisnapdiagnostics.com"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'