apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medisnap-stage
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: medisnap
  source:
    repoURL: git@github.com:ahmadqayyum7/medisnap-helm.git
    targetRevision: main
    path: charts/medisnap
    helm:
      releaseName: medisnap
      valueFiles:
        - ../../envs/stage/medisnap-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true